import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import iconImage from "./courses/music-icon.jpeg"
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Beat-Buddy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark overflow-x-hidden">
      {/* <head>
        <link rel="icon" href="./courses/music-icon.jpeg" type="image/jpeg" sizes="32x32" />
      </head> */}
      <body className={inter.className}>

        <div className=" relative w-full overflow-x-hidden ">
          <Navbar/>
        </div>


        {children}
        
        </body>
    </html>
  );
}
